version: "3.8"

services:
  frontend:
    build: ./apps/client
    container_name: "chess_front"
    volumes:
      - ./apps/client/dist:/app/dist
    networks:
      - multi-chess-nw

  backend_ws:
    build: ./apps/ws
    container_name: "chess_ws"
    networks:
      - multi-chess-nw
    ports: 
      - "8080:8080"
    restart: always

  nginx:
    build: ./nginx
    container_name: "chess_nginx"
    networks:
      - multi-chess-nw
    volumes:
      - ./apps/client/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - frontend

networks:
  multi-chess-nw:
